server:
  port: 8005
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rayson?useSSL=false
    username: root
    password: 199011081108
  application:
    name: point-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: rayest
    username: rayest
    virtual-host: rayson
logging:
  level:
    org.hibernate: debug
    mobi.rayson: debug
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
