application:
  environment:
    console:
      showsql: true
com:
  alipay:
    sofa:
      rpc:
        bolt:
          port: 22202
      tracer:
        datasource:
          enable: false
        zipkin:
          baseUrl: http://127.0.0.1:9411
health:
  alert:
    for_time: 10
logging:
  level:
    com:
      rayest: info
  path: logs
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 18057
server:
  port: 8057
service:
  unique:
    id: ${spring.application.name}
spring:
  application:
    name: sofa-user
