server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: zuul-gateway-service

zuul:
  ignored-services: app-service, music-service
  routes:
    user-api:
      path: /user-api/**
      serviceId: user-service
    order-api:
      path: /order-api/**
      serviceId: order-service
    point-api:
      path: /point-api/**
      serviceId: point-service
    app-bff-api:
      path: /app-api/**
      serviceId: app-bff

