server:
  port: 9527
  servlet:
    context-path: /app

spring:
  application:
    name: sofa-app
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

#日志配置
logging:
  path: logs
  level:
    com:
      rayest: info

service-user:
  unique:
    id: sofa-user

service-order:
  unique:
    id: sofa-order


## sofa rpc 配置。可以通过代码实现配置参考 sofa-common-zookeeper 模块代码
#com:
#  alipay:
#    sofa:
#      rpc:
#        registry-address: zookeeper://127.0.0.1:2181


#  springboot 健康检查
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  server:
    port: 19527
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
