server:
  port: 8200
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rayest/spring-cloud.git
          username: rayest
          password: rayest@1990
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug
