server:
  port: 48080
spring:
  cloud:
    stream:
      kafka:
        binder:
            brokers: localhost:9092

      bindings:
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: stream-demo    #消息发往的目的地
          content-type: text/plain
