server:
  port: 9000
spring:
  application:
    name: app-bff
logging:
  level:
    org.hibernate: debug
    mobi.rayson: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
