server:
  port: 9000
spring:
  application:
    name: app-bff
  cloud:
    alibaba:
      seata:
        tx-service-group: app-bff-fescar-service-group
logging:
  level:
    org.hibernate: debug
    mobi.rayson: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
