server:
    port: 8081
spring:
    application:
        name: output-demo
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
                    auto-add-partitions: true
                    auto-create-topics: true
                    min-partition-count: 1
            bindings:
                default-binder: kafka
                output:
                    destination: event-demo
                    content-type: text/plain
                    producer:
                        partitionCount: 1
            instance-count: 1
            instance-index: 0
